### PR TITLE
Ignore pre-release versions for 'latest'

### PR DESCRIPTION
**Pull request by alexjurkiewicz**

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
Fixes #16

**Comment by paul-pop** [comment]
Is this something that can be merged soon? Probably breaking loads of pipelines because of 0.12 to 0.13 breaking changes.

**Comment by Kjens93** [comment]
@sudomateo 👆

**Comment by sudomateo** [comment]
Hello. I apologize for the delay here. I've actually transitioned to another team at HashiCorp and I am working with product management to find a new maintainer for this repository since I won't have the bandwidth to maintain this repository going forward. I'll get this merged.

**Comment by alexjurkiewicz** [comment]
Thanks for your time spent on the TF actions! It's great to have canonical solutions for this sort of thing.

**Pull request merged**
