### PR TITLE
Do not fail when theres an exit-code 2

### PR DESCRIPTION
**Pull request by dannyibishev**
This should allow plans to succeed using the terraform_wrapper functionality whenever an exit code of `2` is returned.
https://www.terraform.io/docs/cli/commands/plan.html#detailed-exitcode

- This is useful for adding custom steps in our GitHub action workflows.

**Disclaimer:** Im not a Javascript developer so Im not sure how valid the OR condition is.

### CODE REVIEW

**Comment by DariuszPorowski** [comment]
Hey @dannyibishev I am working on the same case as you now, but what I get from GitHub folks is, Actions itself only supports success (0 exit code) vs failure (anything else). So, it's not lack of support in Terraform Actions task, but general behavior of GitHub Actions.

**Comment by jpogran** [comment]
Thanks @DariuszPorowski for the additional detail. We'll need to confirm what the best approach is here

**Comment by brettcurtis** [comment]
We gone through a bit of song and dance here attempting to get apply job to run automatically if no changes to the plan.

```yaml
      - name: Terraform Plan - https://www.terraform.io/docs/commands/plan.html
        id: plan
        run: terraform plan -detailed-exitcode -input=false -out=plan.out ${{ inputs.tf_plan_args}} ${{ secrets.tf_plan_secret_args }}
        continue-on-error: true

      - name: Check for Plan Failure
        if: steps.plan.outputs.exitcode == 1
        run: exit 1

      # Encrypt - Terraform plan.out

      - name: Encrypt Terraform "plan.out"
        if: steps.plan.outputs.exitcode == 2
        run: gpg --quiet --batch --yes --passphrase ${{ secrets.gpg_passphrase }} --symmetric --cipher-algo AES256 plan.out

      # Github - Upload Artifact
      # https://github.com/marketplace/actions/upload-a-build-artifact

      - name: Upload Encrypted Artifact
        if: steps.plan.outputs.exitcode == 2
        uses: actions/upload-artifact@v2
        with:
          name: ${{ inputs.tf_workspace }}-encrypted-plan
          path: ${{ inputs.working_dir }}/plan.out.gpg

    outputs:
      planExitcode: ${{ steps.plan.outputs.exitcode }}

  apply:
    name: "Terraform: apply"
    needs: plan
    if: needs.plan.outputs.planExitcode == 2
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.github_env }}
````

The exit code stuff you guys are talking about gives us the annotation errors and is rather confusing to people.

image

**Comment by jpogran** [comment]
@dannyibishev I've rebased your PR with latest changes so it will pass linting.

I changed the condition to exit early if it is 0 or 2 instead of setting the exit code to be more explicit with our returns. We'll tes this out and get it merged in the 2.1.0 release.

**Comment by bogaertg** [comment]
Hello,

With terraform-wrapper, we always have a response code 0 even if there is changes and option --detailled-exit-code.
[Here](https://github.com/bogaertg/setup-terraform-gh-actions/actions/runs/2407826169) is my testing workflow with a terraform plan and an echo $?.

We cannot return exitCode 2 with the wrapper because of [setFailed](https://github.com/actions/toolkit/blob/main/packages/core/src/core.ts#L213) function.

There is an opened [issue](https://github.com/actions/toolkit/issues/459) for custom exit code.

Maybe, it will be better to add an environnement variable with status code for the wrapper.

**Pull request merged**
