### PR TITLE
Upgrade Nodejs runtime from 12 to 16

### PR DESCRIPTION
**Pull request by chenrui333**
This is consistent with all the recent github action updates. (mostly in `actions` repos, like `actions/checkout`, `actions/setup-node`, etc.)

cc @jpogran

### CODE REVIEW

**Comment by chenrui333** [comment]
It is also desired to make a new release after this PR update.

**Comment by jpogran** [comment]
Thanks for working on this! It was on my list of thing to do, but hadn't gotten to it yet. I admit I'm a bit nervous with the jump from 12 to 16, so we'll have to test this a bunch before we increment the v1 tag.

**Comment by chenrui333** [comment]
> Thanks for working on this! It was on my list of thing to do, but hadn't gotten to it yet. I admit I'm a bit nervous with the jump from 12 to 16, so we'll have to test this a bunch before we increment the v1 tag.

I have to say, there is not much surprise that I have seen so far (ultimately it is just action runner update). :)

**Comment by chenrui333** [comment]
Also, it should be a major upgrade. With the runtime pointing to node16, it would only work Actions Runners v2.285.0 or later.

**Comment by jpogran** [comment]
Good point. I'll create separate milestones. I think the changes so far since last release are fine for 1.4, but a 2.0 for a major runner bump is warranted.

**Comment by chenrui333** [comment]
Sounds good, we can do two releases separately. 👍  😄

**Comment by chenrui333** [comment]
This is actually a blocker for us to use this action with other upgraded actions. :)

**Comment by chenrui333** [comment]
totally, let me refresh my PR.

**Comment by chenrui333** [comment]
Any timeline to merge this PR?

**Comment by jpogran** [comment]
@chenrui333 I'll be reviewing the open PRs this week and determining which land in [2.0](https://github.com/hashicorp/setup-terraform/milestone/2). Look towards that milestone for a delivery date this week

**Comment by magnetikonline** [comment]
> Also, it should be a major upgrade. With the runtime pointing to node16, it would only work Actions Runners v2.285.0 or later.

100% this - follows the same pattern as the `actions/*` GitHub authored action set.

**Comment by jpogran** [comment]
Updating this in preparation for merge

**Comment by chenrui333** [comment]
Sounds good, thanks @jpogran!

**Pull request merged**
