### PR TITLE
Update actions package to 1.2.6

### PR DESCRIPTION
**Pull request by stijndehaes**

### CODE REVIEW

**Review by chenrui333 — APPROVED** [review]
lgtm

**Comment by jontreynes** [comment]
I'm not sure why there is a bad substitution error on this line https://github.com/hashicorp/setup-terraform/blob/f0e69a3f87fe96beb1b75123f7224ee269ec9787/.github/workflows/setup-terraform.yml#L277 @stijndehaes. Other than that, it all looks good

**Comment by jjm** [comment]
> I'm not sure why there is a bad substitution error on this line https://github.com/hashicorp/setup-terraform/blob/f0e69a3f87fe96beb1b75123f7224ee269ec9787/.github/workflows/setup-terraform.yml#L277 @stijndehaes. Other than that, it all looks good

BTW I've got an open PR that corrects that error. 

https://github.com/hashicorp/setup-terraform/pull/59

**Comment by aeschright** [comment]
Hi @stijndehaes -- thanks for submitting this! I needed to take care of a couple of other things at the same time, so I'm closing this in favor of #63 instead. I appreciate the submission.

**Pull request closed without merging**
